// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UpSkills.Infrastructure;

#nullable disable

namespace UpSkills.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227042719_First-Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UpSkills.Infrastructure.Entidades.Pais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Pais", "public");
                });

            modelBuilder.Entity("UpSkills.Infrastructure.Entidades.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol", "users");
                });

            modelBuilder.Entity("UpSkills.Infrastructure.Entidades.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Correo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreadoEn");

                    b.Property<long?>("PaisId")
                        .HasColumnType("bigint");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PrimerApellido");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PrimerNombre");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("text")
                        .HasColumnName("SegundoApellido");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text")
                        .HasColumnName("SegundoNombre");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("PaisId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", "users");
                });

            modelBuilder.Entity("UpSkills.Infrastructure.Entidades.Usuario", b =>
                {
                    b.HasOne("UpSkills.Infrastructure.Entidades.Pais", "Pais")
                        .WithMany("Usuario")
                        .HasForeignKey("PaisId");

                    b.HasOne("UpSkills.Infrastructure.Entidades.Rol", "Rol")
                        .WithMany("Usuario")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("UpSkills.Infrastructure.Entidades.Pais", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UpSkills.Infrastructure.Entidades.Rol", b =>
                {
                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
